create TABLE customer
(
    customer_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stripe_reference VARCHAR(255),
    first_name       VARCHAR(255),
    second_name      VARCHAR(255),
    phone            VARCHAR(255),
    email            VARCHAR(255),
    register_date    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_customer PRIMARY KEY (customer_id)
);

create TABLE customer_order
(
    customer_order_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stripe_reference  VARCHAR(255),
    payment_method    INTEGER,
    payment_currency  INTEGER,
    address           VARCHAR(255),
    city              VARCHAR(255),
    state             VARCHAR(255),
    country           VARCHAR(255),
    zip_code          VARCHAR(255),
    description       VARCHAR(255),
    created           TIMESTAMP WITHOUT TIME ZONE,
    order_status      INTEGER,
    completed         TIMESTAMP WITHOUT TIME ZONE,
    customer_id       BIGINT,
    deleted           BOOLEAN,
    deleted_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_customer_order PRIMARY KEY (customer_order_id)
);

create TABLE customer_order_items
(
    customer_order_id BIGINT NOT NULL,
    id                BIGINT,
    product_id        BIGINT,
    name              VARCHAR(255),
    model             VARCHAR(255),
    quantity          BIGINT,
    unit_price        FLOAT
);

create TABLE product
(
    product_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stripe_reference VARCHAR(255),
    name             VARCHAR(255),
    description      VARCHAR(255),
    price            FLOAT,
    quantity         BIGINT,
    unit_amount      BIGINT,
    shippable        BOOLEAN,
    currency         INTEGER,
    added_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_product PRIMARY KEY (product_id)
);

create TABLE subscription
(
    subscription_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stripe_reference VARCHAR(255),
    name             VARCHAR(255),
    cancel_at        TIMESTAMP WITHOUT TIME ZONE,
    created          TIMESTAMP WITHOUT TIME ZONE,
    currency         INTEGER,
    customer_id      BIGINT,
    description      VARCHAR(255),
    discount         BIGINT,
    status           VARCHAR(255),
    delete_at        TIMESTAMP WITHOUT TIME ZONE,
    deleted          BOOLEAN,
    CONSTRAINT pk_subscription PRIMARY KEY (subscription_id)
);

create TABLE subscription_product_list
(
    product_list_product_id      BIGINT NOT NULL,
    subscription_subscription_id BIGINT NOT NULL
);

alter table customer
    add CONSTRAINT uc_customer_email UNIQUE (email);

alter table customer
    add CONSTRAINT uc_customer_phone UNIQUE (phone);

alter table customer_order
    add CONSTRAINT FK_CUSTOMER_ORDER_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (customer_id);

alter table subscription
    add CONSTRAINT FK_SUBSCRIPTION_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (customer_id);

alter table customer_order_items
    add CONSTRAINT fk_customer_order_items_on_customer_order_entity FOREIGN KEY (customer_order_id) REFERENCES customer_order (customer_order_id);

alter table subscription_product_list
    add CONSTRAINT fk_subprolis_on_product_entity FOREIGN KEY (product_list_product_id) REFERENCES product (product_id);

alter table subscription_product_list
    add CONSTRAINT fk_subprolis_on_subscription_entity FOREIGN KEY (subscription_subscription_id) REFERENCES subscription (subscription_id);